trigger:

  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    include:
      - 'other/ci/i386.yml'
      - 'other/busybox.config'
      - 'kernel/**'
      - 'modules/**'
      - 'include/**'
      - 'common/**'
      - 'boot/**'
      - 'tests/**'
      - 'userapps/**'
      - 'scripts/**'
      - 'config/**'
    exclude:
      - 'README.md'
      - 'docs/**'
      - 'scripts/configurator/**'
      - 'kernel/arch/riscv/**'
      - 'kernel/arch/riscv64/**'
      - 'include/tilck/kernel/arch/riscv/**'
      - 'include/tilck/common/arch/riscv/**'

jobs:
  - job: interactive
    container: 'vvaltchev/tilck-i386:v5'
    pool:
      vmImage: 'ubuntu-24.04'
    variables:
      RUNNING_IN_CI: 1
      TCROOT: /tc/toolchain3-gcc123
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 12.3.0
      CMAKE_ARGS: >
        -DEXTRA_VIM=1
        -DFB_CONSOLE_BANNER=0
        -DFB_CONSOLE_CURSOR_BLINK=0
        -DBOOT_INTERACTIVE=0
        -DPREFERRED_GFX_MODE_W=640
        -DPREFERRED_GFX_MODE_H=480
        -DKMALLOC_FREE_MEM_POISONING=1
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/gcc_gcov
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
      - script: ./build/st/run_interactive_test -a
        displayName: Run the interactive tests

  - job: gcc_12_3
    container: 'vvaltchev/tilck-i386:v5'
    pool:
      vmImage: 'ubuntu-24.04'
    variables:
      RUNNING_IN_CI: 1
      TCROOT: /tc/toolchain3-gcc123
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 12.3.0
      CMAKE_ARGS: >
        -DKERNEL_UBSAN=1
        -DKMALLOC_FREE_MEM_POISONING=1
        -DKERNEL_SAT=1
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests


  - job: coverage
    container: 'vvaltchev/tilck-i386:v5'
    pool:
      vmImage: 'ubuntu-24.04'
    variables:
      RUNNING_IN_CI: 1
      TCROOT: /tc/toolchain3-gcc123
      GTEST_SHUFFLE: 0
      DUMP_COV: 1
      REPORT_COV: 1
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 12.3.0
      CMAKE_ARGS: >
        -DMOD_acpi=0
        -DEXTRA_VIM=1
        -DFB_CONSOLE_BANNER=0
        -DFB_CONSOLE_CURSOR_BLINK=0
        -DBOOT_INTERACTIVE=0
        -DPREFERRED_GFX_MODE_W=640
        -DPREFERRED_GFX_MODE_H=480
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/gcc_gcov
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/scripts/generate_test_coverage_report
        displayName: Gen unit tests coverage report
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
      - script: ./build/st/run_interactive_test -a
        displayName: Run the interactive tests
      - script: ./build/scripts/generate_kernel_coverage_report --codecov
        displayName: Gen kernel gcov report and upload to codecov
      - script:
          python3 -m coverage run -m unittest discover scripts/configurator/parser/
        displayName: 'CMake-configurator: run unit tests'
      - script: |
          python3 -m coverage report
          python3 -m coverage xml
        displayName: 'CMake-configurator: generate coverage report'
      - script: ./build/tmp/codecov
        displayName: 'Run codecov'
